import { FileText, Download } from "lucide-react";
import jsPDF from "jspdf";
import type { WeeklyReport } from "@/lib/reflectionAnalytics";

interface Props { report: WeeklyReport }

const exportPdf = (r: WeeklyReport) => {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const width = pdf.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.text("Weekly Mood Report", margin, y);
  y += 24;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(110);
  pdf.text(`${r.startDate} – ${r.endDate}`, margin, y);
  y += 28;

  pdf.setTextColor(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(13);
  pdf.text("Reflection Score", margin, y);
  y += 16;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(
    `Total ${r.reflection.total}/100  •  Stability ${r.reflection.stability}  •  Positivity ${r.reflection.positivity}  •  Consistency ${r.reflection.consistency}`,
    margin,
    y,
  );
  y += 22;

  const section = (title: string, body: string | string[]) => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.text(title, margin, y);
    y += 16;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);
    const lines = Array.isArray(body) ? body : [body];
    lines.forEach((l) => {
      const wrapped = pdf.splitTextToSize(`• ${l}`, width - margin * 2);
      pdf.text(wrapped, margin, y);
      y += wrapped.length * 14;
    });
    y += 10;
  };

  section("Mood trend", r.trendSummary);
  if (r.behaviorInsights.length) section("Behavior insights", r.behaviorInsights);
  section("Biggest positive factor", r.biggestPositive);
  section("Biggest negative factor", r.biggestNegative);
  section("Suggestion", r.suggestion);

  pdf.setTextColor(140);
  pdf.setFontSize(9);
  pdf.text("Generated by Mood Mirror — for personal reflection only.", margin, 800);

  pdf.save(`mood-mirror-report-${r.endDate.replace(/[, ]+/g, "-")}.pdf`);
};

export const WeeklyReportSection = ({ report }: Props) => {
  return (
    <section className="rounded-3xl glass p-5 shadow-card space-y-4">
      <div className="flex items-center gap-2">
        <FileText className="h-4 w-4 text-accent" />
        <h2 className="text-[11px] font-semibold uppercase tracking-[0.25em] text-accent">
          Weekly Mood Report
        </h2>
        <span className="ml-auto text-[10px] text-muted-foreground">
          {report.startDate} – {report.endDate}
        </span>
      </div>

      <p className="text-sm font-light leading-relaxed">{report.trendSummary}</p>

      {report.behaviorInsights.length > 0 && (
        <div className="space-y-1.5">
          <p className="text-[11px] uppercase tracking-[0.2em] text-accent/80">Behavior insights</p>
          {report.behaviorInsights.map((b, i) => (
            <p key={i} className="text-xs text-muted-foreground font-light">• {b}</p>
          ))}
        </div>
      )}

      <div className="grid grid-cols-2 gap-3">
        <div className="rounded-2xl bg-emerald-500/10 border border-emerald-400/20 p-3">
          <p className="text-[10px] uppercase tracking-[0.18em] text-emerald-300 mb-1">Biggest positive</p>
          <p className="text-xs font-light">{report.biggestPositive}</p>
        </div>
        <div className="rounded-2xl bg-rose-500/10 border border-rose-400/20 p-3">
          <p className="text-[10px] uppercase tracking-[0.18em] text-rose-300 mb-1">Biggest drag</p>
          <p className="text-xs font-light">{report.biggestNegative}</p>
        </div>
      </div>

      <div className="rounded-2xl bg-accent/10 border border-accent/20 p-3">
        <p className="text-[10px] uppercase tracking-[0.18em] text-accent mb-1">Suggestion</p>
        <p className="text-xs font-light">{report.suggestion}</p>
      </div>

      <button
        onClick={() => exportPdf(report)}
        className="w-full rounded-full glass-strong shadow-glow py-2.5 text-xs uppercase tracking-[0.2em] text-accent flex items-center justify-center gap-2 hover:brightness-110 transition-smooth"
      >
        <Download className="h-3.5 w-3.5" />
        Export as PDF
      </button>
    </section>
  );
};
